networks:
  work:

services:
  nginx:
    image: nginx:1.21.0-alpine
    container_name: nginx-work
    environment:
      TZ: Europe/Kiev
    ports:
      - "80:80" #Если ругается что какой-то порт занят попробуйте сменить первую 80 на что-то другое, допустим на - "83:80"
      - "449:443" #Если ругается что какой-то порт занят попробуйте сменить первую 443 на что-то другое, допустим на - "444:443"
    volumes:
      - ./src:/var/www/src
      - ./nginx/logs:/var/log/nginx #логи будут "синхронизироватся" в эту папку (nginx/logs)
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf #пробрасываем конфиг в нужную папку
    networks:
      - work

  node:
    image: node:latest
    container_name: nodework
    environment:
      TZ: Europe/Kiev
    volumes:
      - ./client:/var/www/
    working_dir: /var/www/
    entrypoint: ['npm', 'run', 'dev']
    ports:
      - '5174:5173'
    networks:
      - work

  php:
    build:
      context: ./php-cli
      dockerfile: Dockerfile
    container_name: php-work
    environment:
      TZ: Europe/Kiev
    volumes:
      - ./src:/var/www/src
    networks:
      - work

  reverb:
    build:
      context: ./php-cli
      dockerfile: cli.Dockerfile
    container_name: reverb
    environment:
      TZ: Europe/Kiev
    ports:
      - '8080:8080'
    volumes:
      - ./src:/var/www/src
    depends_on:
      - mysql
    working_dir: /var/www/src
    entrypoint: [ "php", "/var/www/src/artisan", "reverb:start" ]
    networks:
      - work

  mysql:
    image: mysql:8.0
    container_name: mysql-work
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
      TZ: Europe/Kiev
      MYSQL_DATABASE: palmo
      MYSQL_USER: palmo
      MYSQL_PASSWORD: palmo
      MYSQL_ROOT_PASSWORD: palmo
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - work

  artisan:
    build:
      context: ./php-cli
      dockerfile: Dockerfile
    container_name: artisan
    environment:
      TZ: Europe/Kiev
    volumes:
      - ./src:/var/www/src
    depends_on:
      - mysql
    working_dir: /var/www/src
    entrypoint: ["php", "/var/www/src/artisan"]
    user: "1000:1001"
    networks:
      - work


  redis:
    image: redis:alpine
    container_name: redis-work
    ports:
      - "6379:6379"
    networks:
      - work